- src/main/java/in/tech_camp/protospace_c/controller/PrototypeController.java
- src/main/resources/static/css/prototypeStyle.css
- src/main/resources/templates/prototype/new.html
> プロトタイプ登録ビューの作成

- build.gradle
- src/main/java/in/tech_camp/protospace_c/SecurityConfig.java
- src/main/java/in/tech_camp/protospace_c/controller/UserController.java
- src/main/java/in/tech_camp/protospace_c/entity/UserEntity.java
- src/main/java/in/tech_camp/protospace_c/form/UserForm.java
- src/main/java/in/tech_camp/protospace_c/repository/UserRepository.java
- src/main/java/in/tech_camp/protospace_c/service/UserService.java
- src/main/java/in/tech_camp/protospace_c/validation/ValidationOrder.java
- src/main/java/in/tech_camp/protospace_c/validation/ValidationPriority1.java
- src/main/java/in/tech_camp/protospace_c/validation/ValidationPriority2.java
> initial commit for user signup

- src/main/java/in/tech_camp/protospace_c/controller/PrototypeController.java
- src/main/resources/templates/prototypes/edit.html
- src/main/resources/templates/prototypes/new.html
> プロトタイプ編集ビューの作成

- src/main/java/in/tech_camp/protospace_c/controller/PrototypeController.java
- src/test/java/in/tech_camp/protospace_c/controller/PrototypeControllerTest.java
> プロトタイプ編集機能の実装

- src/main/java/in/tech_camp/protospace_c/controller/PrototypeController.java
- src/main/resources/application.properties
- src/test/java/in/tech_camp/protospace_c/form/PrototypeFormUnitTest.java
functional code and unit test for creating new prototype
for issue #7
> Prototype create

- src/main/java/in/tech_camp/protospace_c/controller/PrototypeController.java
- src/main/resources/static/css/style.css
- src/main/resources/templates/header.html
- src/main/resources/templates/index.html
ログイン状態による表示の変更
ログイン状態で、ログアウト、新規投稿
ログアウト状態で、新規登録、ログイン
の機能を使えるようにするため。
> ログイン状態による表示の変更

- src/main/java/in/tech_camp/protospace_c/SecurityConfig.java
- src/main/java/in/tech_camp/protospace_c/repository/PrototypeRepository.java
- src/main/resources/templates/index.html
- src/main/resources/templates/users/detail.html
> fix: プロトタイプの表示修正

- src/main/java/in/tech_camp/protospace_c/controller/UserController.java
ユーザー新規登録後の自動ログイン
新規登録後にログインする手間を省くため
> ユーザー新規登録後の自動ログイン

- src/main/java/in/tech_camp/protospace_c/SecurityConfig.java
- src/main/java/in/tech_camp/protospace_c/controller/CommentController.java
- src/main/java/in/tech_camp/protospace_c/controller/PrototypeController.java
- src/main/java/in/tech_camp/protospace_c/repository/PrototypeRepository.java
- src/main/resources/templates/prototypes/detail.html
front end and backend modification for prototype detail & comment
for issue #9 and issue #13
> front end and backend modification for prototype detail & comment

- src/main/java/in/tech_camp/protospace_c/controller/PrototypeController.java
- src/test/java/in/tech_camp/protospace_c/factory/PrototypeFactory.java
- src/test/java/in/tech_camp/protospace_c/system/DeletePrototypeTest.java
- src/test/java/in/tech_camp/protospace_c/system/PostPrototypeTest.java
- src/test/java/in/tech_camp/protospace_c/system/PutPrototypeTest.java
プロトタイプ登録/ 編集/ 削除機能のテスト実装
プロトタイプ周りの挙動を確認するため
> プロトタイプ機能のテスト実装

- src/test/java/in/tech_camp/protospace_c/system/GetPrototypesByUserIdTest.java
userIdを使用したプロトタイプ取得機能のテスト
userIdを使用したプロトタイプ取得機能の挙動確認
> userIdを使用したプロトタイプ取得機能のテスト

- src/main/java/in/tech_camp/protospace_c/controller/UserController.java
- src/main/java/in/tech_camp/protospace_c/repository/UserRepository.java
- src/main/java/in/tech_camp/protospace_c/service/UserService.java
- src/main/resources/templates/users/detail.html
- src/main/resources/templates/users/edit.html
> ユーザー情報編集機能

- src/main/java/in/tech_camp/protospace_c/SecurityConfig.java
- src/main/java/in/tech_camp/protospace_c/controller/PrototypeController.java
- src/main/java/in/tech_camp/protospace_c/form/SearchForm.java
- src/main/java/in/tech_camp/protospace_c/repository/PrototypeRepository.java
- src/main/resources/static/css/style.css
- src/main/resources/templates/prototypes/search.html
added backend code for search function, the search function can be used in the top page, and user who are not logged in can see the searching results too. Also, the looks of the search form and the comment area of prototype detail page are restyled.
for issue #54
> initial commit for the search function

- src/main/java/in/tech_camp/protospace_c/SecurityConfig.java
- src/main/java/in/tech_camp/protospace_c/controller/LikesController.java
- src/main/java/in/tech_camp/protospace_c/controller/UserController.java
- src/main/resources/static/css/style.css
- src/main/resources/static/js/like_button.js
- src/main/resources/templates/index.html
- src/main/resources/templates/prototypes/detail.html
- src/main/resources/templates/users/detail.html
いいねボタンの非同期化といいねしたプロトタイプの表示
いいねボタンの非同期化によるUXの向上
> いいねボタンの非同期化といいねしたプロトタイプの表示

- src/main/java/in/tech_camp/protospace_c/controller/LikesController.java
- src/main/resources/static/css/style.css
- src/main/resources/static/js/like_button.js
- src/main/resources/templates/index.html
- src/main/resources/templates/prototypes/detail.html
- src/main/resources/templates/users/detail.html
マイページにいいねしたプロトタイプを表示
自分がいいねしたプロトタイプを確認できるようにするため
> マイページにいいねしたプロトタイプを表示

- src/main/java/in/tech_camp/protospace_c/SecurityConfig.java
- src/main/java/in/tech_camp/protospace_c/WebConfig.java
- src/main/java/in/tech_camp/protospace_c/controller/UserController.java
- src/main/java/in/tech_camp/protospace_c/repository/UserRepository.java
- src/main/resources/static/css/style.css
- src/main/resources/static/js/like_button.js
- src/main/resources/templates/header.html
- src/main/resources/templates/index.html
- src/main/resources/templates/prototypes/detail.html
- src/main/resources/templates/users/detail.html
各種ページでユーザーアイコンの表示機能の実装
ユーザーアイコンを表示することで、視認性を高める
> ユーザーアイコンの表示

- src/main/java/in/tech_camp/protospace_c/controller/CommentController.java
- src/main/resources/static/js/comment.js
- src/main/resources/templates/fragments/commentItem.html
Not brush up the whole page when deleting a comment
> initial commit for asynchronous comment delete

- src/main/resources/static/css/style.css
- src/main/resources/static/js/prototype_preview.js
- src/main/resources/templates/prototypes/edit.html
- src/main/resources/templates/prototypes/new.html
プロトタイプ登録 / 編集ページでの画像プレビュー実装
プロトタイプ登録 / 編集時に画像を表示することで、誤った画像の登録を防ぐ
> プロトタイプ登録 / 編集ページでの画像プレビュー実装

- src/main/resources/static/css/style.css
- src/main/resources/templates/prototypes/edit.html
- src/main/resources/templates/prototypes/new.html
- src/main/resources/templates/users/signUp.html
> プロトタイプ登録・編集フォームのスタイル修正

- src/main/java/in/tech_camp/protospace_c/controller/PrototypeController.java
- src/main/java/in/tech_camp/protospace_c/repository/GenreRepository.java
- src/main/resources/application.properties
- src/main/resources/static/css/style.css
- src/main/resources/templates/index.html
- src/main/resources/templates/prototypes/genre.html
> ジャンル検索の表示、修正

- src/main/java/in/tech_camp/protospace_c/controller/PrototypeController.java
- src/main/java/in/tech_camp/protospace_c/controller/UserController.java
- src/main/resources/static/css/style.css
- src/main/resources/templates/prototypes/edit.html
- src/main/resources/templates/users/detail.html
> 各所スタイル修正とエラー文の日本語表示
